version: "3.9"
services:
  app:
    container_name: app
    build: ./infra/php
    volumes:
      - ./src:/data
  web:
    container_name: web
    image: nginx:1.20-alpine
    ports:
      - 8080:80
    volumes:
      - ./src:/data
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /data
  db:
    container_name: db
    build: ./infra/mysql
    platform: linux/x86_64
    volumes:
      - db-store:/var/lib/mysql
    ports:
      - 33060:3306
  db-test:
    container_name: db-test
    build: ./infra/mysql-test
    platform: linux/x86_64
    ports:
      - 33061:3306
volumes:
  db-store:
